baseurl      = "https://pivrous.wtf"
title        = "Pivrous"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

contentDir   = "content"
publishDir   = "public"

[author]
  name = "Pierre Averous"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Site Reliability Engineer <a href='https://padok.fr/'>@Padok</a>"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]
  
  [params.portrait]
    path     = "./img/profile.jpg"
    alt      = "Portrait"
    maxWidth = "100px"
    
  [[params.social]]
    name = "github"
    url = "https://github.com/piaverous"

  [[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/piaverous"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/pierre-averous/"

  [[params.social]]
    name = "medium"
    url = "https://piaverous.medium.com"

  [params.footer]
    trademark = true
    rss = true
    author = true

    topText = []
    bottomText = []

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Pierre Averous"
    subtitle = "Site Reliability Engineer @Padok"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoMark     = ">"
      logoText = "$ curl pivrous.wtf"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "experiments"
    name       = "Experiments"
    url        = "/experiments"